<?xml version="1.0"?>
<package format="3">
  <name>quadruped_kinematics</name>
  <version>0.1.0</version>
  <description>
    Core kinematics library for quadruped robots:
    leg IK, body IK, and Bezier-based foot trajectories.
  </description>

  <maintainer email="skynguyen313@gmail.com">skynguyen</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>quadruped_core</depend>
  <depend>Eigen3</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
